#!/bin/sh
#alias this eg `git cscope' is aliased to `!~/.git_template/hooks/cscope'
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.cscope"' EXIT
git ls-files > git-files
cscope -b -i git-files
mv "cscope.out" "$dir/cscope.out"
